### ISSUE TITLE
Specific Heat

### ISSUE THREAD

**Issue by hbadi** [MadsKirkFoged/EngineeringUnits#18]
Hi,

I didn't find the specific heat Cp [J.kg.K], did i miss something ? If no, is there a way to extend or derive this new unit as  power/(surface*temperature) ?

Best regards.

**Comment by MadsKirkFoged** [comment]
There is `SpecificEntropy` which have the same units [JoulePerKilogramKelvin]

Will that do it for you?

**Comment by hbadi** [comment]
Hello @MadsKirkFoged 
Yes it works ! Thanks.
It'd be great to create a custom dimension using a formula created with existing variable.
Best regards.

**Comment by MadsKirkFoged** [comment]
*Edit just rechanged the name to SpecificHeatCapacity

I have added `SpecificHeatCapacity` as an alias to SpecificEntropy

It can be used like this:

```C#
SpecificEntropy S1 = new SpecificEntropy(10, SpecificEntropyUnit.JoulePerKilogramKelvin);
SpecificHeatCapacity S2 = new SpecificEntropy(10, SpecificEntropyUnit.JoulePerKilogramKelvin);
SpecificHeatCapacity S3 = new SpecificHeatCapacity (10, SpecificEntropyUnit.JoulePerKilogramKelvin);
SpecificHeatCapacity S4 = S1;
```

You can find it in the newest version
