### ISSUE TITLE
Power Zero gives incorrect result

### ISSUE THREAD

**Issue by jccockre** [MadsKirkFoged/EngineeringUnits#2]
Currently the BaseUnit will return itself when asked to raise itself to the zeroth power.

Real numbers raised to the zeroth power are defined to be one, and dimensional quantities to the zeroth power are dimensionless.

I have a fix including unit tests but getting 403 error when trying to submit a pull request; maybe I need you to grant me permissions or maybe I don't know how to use Git.

**Comment by jccockre** [comment]
Simple method for Pow:

```
        public UnknownUnit Pow(int toPower)
        {
            UnknownUnit output = this;
            
            while (toPower > 1)
            {
                output = output * this;
                toPower--;
            }

            while (toPower < 1)
            {
                output = output / this;
                toPower++;
            }

            return output;
        }
```

**Comment by jccockre** [comment]
Unit test:

```
        [TestMethod]
        public void Pow()
        {
            Length twoMeters = Length.From(2, LengthUnit.Meter);

            var powMinus2 = twoMeters.Pow(-2);
            var powMinus1 = twoMeters.Pow(-1);
            var pow0 = twoMeters.Pow(0);
            var pow1 = twoMeters.Pow(1);
            var pow2 = twoMeters.Pow(2);
            var pow3 = twoMeters.Pow(3);

            Assert.AreEqual(Math.Pow(2, -2), powMinus2.Value);
            Assert.AreEqual(Math.Pow(2, -1), powMinus1.Value);
            Assert.AreEqual(Math.Pow(2, 0), pow0.Value);
            Assert.AreEqual(Math.Pow(2, 1), pow1.Value);
            Assert.AreEqual(Math.Pow(2, 2), pow2.Value);
            Assert.AreEqual(Math.Pow(2, 3), pow3.Value);
        }
```

**Comment by jccockre** [comment]
I just realized the same change needs to be made in `UnitSystem`.

**Comment by MadsKirkFoged** [comment]
Thank you @jccockre for contribution to make this system better!
You are right, the `Pow(0)` didnt work correctly!

You should be able to create pull requests.

I have added the `Pow(0)` case for you and used your unit test.
Can you test it to check if I have done it correctly?

**Comment by jccockre** [comment]
The test passes, so it will do everything I need it to do in my application. Therefore, it is correct! 

If you care to discuss further, I'm curious to understand why `UnitSystem:Pow(0)` should return `this` as opposed to `local`, when `this` might have a unit e.g. `Meter` whereas `Pow(0)` should be dimensionless scalar.

In general any non-zero quantity `q` raised to the zeroth power is `q / q` which is a dimensionless 1.

**Comment by MadsKirkFoged** [comment]
@jccockre a mistake on my side. You are right `UnitSystem:Pow(0)` should return `local`
Just fixed that!
Thank for asking the right questions!
