### ISSUE TITLE
New unit: Molar flow

### ISSUE THREAD

**Issue by mschmitz2** [MadsKirkFoged/EngineeringUnits#25]
Molar flow (i.e. `AmountOfSubstance`/ `Duration` e.g. mol/s) is a unit that would be of interest for me. 

Specifically, I ran into needing to compute `MassFlow` / `MolarMass`, which I then noticed I could not cast to anything appropriate.

Thanks for the amazing work!

**Comment by MadsKirkFoged** [comment]
It sounds like something that needs to be added!
I'll have a look at it after the summer holidays :-)

**Comment by mschmitz2** [comment]
No hurry. I took inspiration from your source code and defined a couple of units myself.

Example of unit in question, with minimal number of units (SI & mol/s): [MolarFlowUnit.zip](https://github.com/MadsKirkFoged/EngineeringUnits/files/9166143/MolarFlowUnit.zip).

**Comment by MadsKirkFoged** [comment]
I have added the MolarFlow in the newest version  .
Can you test it out and see if it matches your expectations?

```C#
AmountOfSubstance Mole = new AmountOfSubstance(10, AmountOfSubstanceUnit.Mole);
Duration Time = new Duration(5, DurationUnit.Second);
MolarFlow MF = Mole / Time;
```

**Comment by mschmitz2** [comment]
Works as expected for all my current uses. Can get rid of my implementation. Thanks.
