### ISSUE TITLE
New unit: volumetric heat transfer coefficient

### ISSUE THREAD

**Issue by mschmitz2** [MadsKirkFoged/EngineeringUnits#30]
I.e. Power / (Volume * Temperature), e.g. W/m^3.K

My own implementation for reference: 
[VolumetricHeatTransferCoefficient.zip](https://github.com/MadsKirkFoged/EngineeringUnits/files/9349029/VolumetricHeatTransferCoefficient.zip)

**Comment by MadsKirkFoged** [comment]
added!
