### ISSUE TITLE
Null comparison with operator throws NullReferenceException

### ISSUE THREAD

**Issue by JFReni** [MadsKirkFoged/EngineeringUnits#31]
```
Temperature? temperature = GetTemperatureFromMethodThatCouldReturnNull();

if(temperature == null)
{
   ...
}
```

The null comparison in the if statement throws because it uses the overloaded `==` operator for BaseUnit vs BaseUnit which calls: 

`if (left.Unit != right.Unit)`

When right is null such as the comparison above this throws a NullReferenceException.

**Comment by MadsKirkFoged** [comment]
Hi [JFReni](https://github.com/JFReni)

Thank you for reporting this bug! I have fixed it however it is not recommended in C# to use `==` as nullcheck.
Instead use the `is null` or `is not null`

```C#
Temperature temperature2 = null;

//Not recommended!
if (temperature2 == null)
{                
}

//Recommended!
if (temperature2 is null)
{
}

//Recommended!
if (temperature2 is not null)
{
}
```
