### ISSUE TITLE
ToString() without scientific notation

### ISSUE THREAD

**Issue by mbrown-dlb** [MadsKirkFoged/EngineeringUnits#60]
If a unit has a large value (>10000) the .ToString() automatically displays the value with scientific notation. Is there a way to override this behavior?

**Comment by MadsKirkFoged** [comment]
You can use the formats:
https://github.com/MadsKirkFoged/EngineeringUnits?tab=readme-ov-file#what-are-my-options-for-outputting-to-a-string


    
```
Pressure LargeNumber = Pressure.FromBar(1000000);

string PrintOut = LargeNumber.ToString();  //1e+06 bar
string PrintOut2 = LargeNumber.ToString("S7"); //1000000 bar
string PrintOut3 = LargeNumber.ToString("G7"); //1000000 bar
```
