### ISSUE TITLE
Support for specific thermal resistance / thermal resistivity (K⋅m/W)

### ISSUE THREAD

**Issue by ikijano** [MadsKirkFoged/EngineeringUnits#9]
It would be nice if EngineeringUnits would support thermal resistivity unit (K⋅m/W) that would be helpful.

**Comment by MadsKirkFoged** [comment]
Hi Ikijano,

I have added SpecificThermalResistance to the library:
```
            SpecificThermalResistance STR = new SpecificThermalResistance(10,SpecificThermalResistanceUnit.MeterKelvinPerKilowatt);
            SpecificThermalResistance STR2 = (Length.FromMeters(3.2) * Temperature.FromKelvins(10)) / Power.FromWatts(23);

            ThermalConductivity TC = 1/STR;
```

Was this what you were looking for?
Can you test the new version of the nuget and report back if you find a bug?

**Comment by ikijano** [comment]
Hi MadsKirkFoged,

I have played around a little bit. Seems to work OK, but with one addition. SI getter need to be added otherwise SI value is 1000 times smaller. I forked repo and made changes and unit test.

I made pull request #10
